+UserDetails
PRO-E-montazysta/PRO pull request #127
Opened 2023-03-24 19:39 UTC by s18288

2023-03-24 19:39 UTC, s20146 commented
Task linked: [CU-862j3czyx CompanyAdminComponent](https://app.clickup.com/t/862j3czyx)

2023-03-24 21:05 UTC, kurylek requested changes
On `/users` u can only create Cloud_Admin. Empolyees have to be created on their role endpoint (eg. `/fitter`)
AppUser model has also `username` and `roles`
Create form don't work
Try to use list that @Marcin-H created, insted of making new one

2023-04-08 17:47 UTC, kurylek requested changes, later dismissed
Wymagane tłumaczenie pól formularzy/ról pracownika.
Brak możliwości edycji/usunięcia pracownika.
Należy ograniczyć dostęp do podstron, tak aby nie były widoczne przez każdego.

2023-04-08 17:47 UTC, kurylek commented on React/src/pages/employees/employeesDetails/EmpDetails.tsx
> +            <FormLabel label="Phone" formik={formik} id={'phone'} />
```suggestion
            <FormLabel label="E-mail" formik={formik} id={'email'} />
            <FormLabel label="Hasło" formik={formik} id={'password'} />
            <FormLabel label="Nazwa użytkownika" formik={formik} id={'username'} />
            <FormLabel label="Status" formik={formik} id={'status'} />
            <FormLabel label="Stanowisko" formik={formik} id={'roles'} />
            <FormLabel label="Telefon" formik={formik} id={'phone'} />
```

2023-04-08 17:47 UTC, kurylek commented on React/src/types/model/Employee.ts
>  }
Stanowiska powinny być przetłumaczone.
Do tego pytanie, czy nazwa 'RoleStatus' jest tutaj odpowiednia- to jest rola (stanowisko) a nie status

2023-04-08 17:47 UTC, kurylek commented on React/src/helpers/enum.helper.ts
> +export const roleStatusOptions = () => {
`roleStatusOptions` raczej nie jest pasującą nazwą

2023-04-08 21:16 UTC, kurylek commented on React/src/pages/employees/helper.ts
> +    pesel: yup.string().length(11,'Wymagany jest poprawny pesel').required('Wprowadź email')
```suggestion
    pesel: yup.string().length(11,'Wymagany jest poprawny pesel').required('Wprowadź pesel')
```
Pozostałość przy kopiowaniu

2023-04-14 20:10 UTC, kurylek approved these changes

2023-04-14 20:11 UTC, merged

2023-04-14 20:13 UTC, s21461 approved these changes