Cu 862jev22r testy ekranu dodaj zlecenie/lista zlecen krzysztof maj
PRO-E-montazysta/PRO pull request #143
Opened 2023-04-04 17:31 UTC by KrzysztofMaj-s18533

Added AddTaskTest.java and ListTaskTest.java test suites with 4 tests inside each

2023-04-04 17:31 UTC, s20146 commented
Task linked: [CU-862jev22r Testy ekranu Dodaj Zlecenie](https://app.clickup.com/t/862jev22r)

2023-04-04 18:36 UTC, kurylek requested changes
Task wysłany w ramach testów, a wprowadza zmiany w androidzie. Do tego jakieś dzikie .idea

2023-04-05 17:38 UTC, s20439 commented
@KrzysztofMaj-s18533 Tak jak kamil napisał, popraw to prosze.

2023-04-11 16:51 UTC, KrzysztofMaj-s18533 commented
Jasne - w gwoli zrozumienia - tutaj zmiany w androidzie faktycznie są, postaram się je wycofać, ale siedzieliśmy razem z Krzyśkiem Sidorem żeby to po prostu działało, bo Staszek zhardcodował ścieżkę do swojego .idea - z tego co wiem, na lokalnej wersji androida u @ksidor93 też są tego typu i podobne zmiany - u mnie też po prostu mam inaczej z wersją javy, inne ścieżki, z tego powodu te zmiany.
A @kurylek co do .idea, jak spojrzysz jedyne co się tam zmienia to usunięcie newline na końcu, czyli różnica żadna/kosmetyczna - jednak z androidem postaram się ogarnąć, żeby nie było konfliktów, jednak mimo wszystko musimy jakoś to rozwiązać w ramach Androida, żeby się odpalało przy tym, że wszyscy będą mieli jedną wersję tych plików, bo aktualna wersja jest przestarzała i wymaga takich właśnie manualnych zmian żeby działać na konkretnych komputerach

2023-04-11 17:04 UTC, KrzysztofMaj-s18533 commented
[Android/app/src/main/res/drawable/button.xml](https://github.com/s20146/PRO/pull/143/files#diff-51c541790005f39ff306d746ce19881525877dc3c26ee406f5483dc8cb3b53bf)

- tu zmiana jest uzasadniona, bo to nie działało wcześniej, co @ksidor93 potwierdzi, siedzieliśmy nad tym razem;

[Android/gradle/wrapper/gradle-wrapper.properties](https://github.com/s20146/PRO/pull/143/files#diff-920399ff1cb56b2f5dd8cf52b8285f5a4c07e793368ef8f600a388eaf26b4727)

- tu zmiana jest uzasadniona, bo przy Gradle niższym niż 7.5 niedostępny jest design view w androidzie;

[Android/.gradle/buildOutputCleanup/cache.properties](https://github.com/s20146/PRO/pull/143/files#diff-fdd238c624611fdba9308fbc56fb9f13dabf6c83352ad6eac926af938d6fb9aa)

- podobnież;

[Android/local.properties](https://github.com/s20146/PRO/pull/143/files#diff-2339162cadbbcfa36d6394f1f89199a7efcf67502801aae24cb4612a13dbfe6a)

- tu zmienię ALE zauważcie, że w pliku zhardcodowana jest ścieżka na dysku Staszka, co nie ma prawa działać na innych komputerach - z oczywistych powodów. Da się to zastąpić generyczną ścieżką do aktualnego usera może? Zróbmy tak, żeby to wszystkim zaczęło działać, zamiast wracać do niedziałającej wersji;

[Android/.idea/gradle.xml](https://github.com/s20146/PRO/pull/143/files#diff-b036dd32205f6ba1acef648950746dbba62807e153c7ed523cab5eda96bce6bd)

- tu kwestia mojej wersji JVM, zmienię zaraz;

[Android/.idea/misc.xml](https://github.com/s20146/PRO/pull/143/files#diff-e3c88127fca5e1128b0d3a5782cdcb079bb773d12af4b02d74ce2d7abc2b68db)

- tu również kwestia wewnętrznych ustawień na moim komputerze, żeby to działało, postaram się to zmienić zaraz.

2023-04-11 17:28 UTC, KrzysztofMaj-s18533 commented
[.idea/misc.xml](https://github.com/s20146/PRO/pull/143/files#diff-7ea1cd7bd5d16299a0abd33128e8d0a8bc04146f6b00c07bcd3cc0aad813c229)

- to mi się dodaje kiedy otwieram folder PRO jako IntelliJ Idea Project automatycznie i jest identyczne do tego co w Pull Request.

[.idea/vcs.xml](https://github.com/s20146/PRO/pull/143/files#diff-a6dab70bd0e9ffc91d8419ad52225baff3a3e7c9d8e1724f7ed6d96b661d804a)
 
- to mi się dodaje kiedy otwieram folder PRO jako IntelliJ Idea Project automatycznie i jest identyczne do tego co w Pull Request.

[.idea/workspace.xml](https://github.com/s20146/PRO/pull/143/files#diff-9f043e4e89d784b579b6d75ea8704b232f9475fa5b3afd11f805fdf8e74c675c)

- to mi się dodaje kiedy otwieram folder PRO jako IntelliJ Idea Project automatycznie i różni się od pliku w Pull Request. Z tego co widzę, zapisuje takie lokalne rzeczy, jak plik który ostatnio wyświetlałem, albo to, żeby domyślnie pliki otwierać/nie otwierać w design view.

[.idea/modules.xml](https://github.com/s20146/PRO/pull/143/files#diff-0aae258f1732eac2acd4fcdd1af6d0737b4ec8d233136c3ba7c40b6d49aeda50)

- to mi się w ogóle nie dodało po otwarciu jako projekt IntelliJ Idea, nie wiem do czego to konkretnie służy, ale możemy/mogę posprawdzać, żeby rozjaśnić sprawę.

[.idea/PRO.iml](https://github.com/s20146/PRO/pull/143/files#diff-d607c46d913632c62449b96285dc5904f1149d0d23537199ba80f597b434dd7d)

- nie wiem do czego to służy, może tworzy się przy kompilacji? również mi się w ogóle nie dodało po otwarciu jako projekt IntelliJ Idea.

2023-04-15 07:49 UTC, s20439 approved these changes
ok

2023-04-15 07:53 UTC, kurylek approved these changes

2023-04-15 07:54 UTC, merged