Obsługa powiadomień dla częśći przypadków
PRO-E-montazysta/PRO pull request #200
Opened 2023-05-07 20:19 UTC by s21670-Pyrzak-Tomasz-gr-18C

2023-05-07 20:19 UTC, ksidor93 commented
Task linked: [CU-861mq302g Implementation of notifications new](https://app.clickup.com/t/861mq302g)

2023-05-08 19:32 UTC, kurylek requested changes
Poprawię co trzeba, żeby śmigało jak trzeba! :D

2023-05-08 19:32 UTC, kurylek commented on Java/E-montazysta/src/main/java/com/emontazysta/repository/OrderRepository.java
> +    public Optional<Orders> findById(Long id);
Nie jestem pewny, czy to nie jest już z góry zaimplementowane

2023-05-08 19:32 UTC, kurylek commented on Java/E-montazysta/src/main/java/com/emontazysta/service/impl/NotificationServiceImpl.java
> +    }
Powinniśmy to jakoś sprytnie ograć jednym konstruktorem

2023-05-08 19:32 UTC, kurylek commented on Java/E-montazysta/src/main/java/com/emontazysta/service/impl/OrderStageImpl.java
> +        orderStage.getOrders().setStatus(OrderStatus.PLANNING);
Ogramy to przez zmiany statusów z poziomu Order'a

2023-05-08 19:32 UTC, kurylek commented on Java/E-montazysta/src/main/java/com/emontazysta/service/impl/OrdersServiceImpl.java
> +        order.setEditedAt(LocalDateTime.now());
```suggestion
        order.setEditedAt(null);
```
Przy tworzeniu czas edycji nie istnieje

2023-05-08 19:32 UTC, kurylek commented on Java/E-montazysta/src/main/java/com/emontazysta/service/impl/OrdersServiceImpl.java
> +
Zmiany statusu Order'a ograłbym specjalnym endpointem

2023-05-08 19:32 UTC, kurylek commented on Java/E-montazysta/src/main/java/com/emontazysta/service/impl/OrdersServiceImpl.java
> +    }
Wydzieliłbym gdzieś te metodę

2023-05-09 16:57 UTC, kurylek approved these changes
Should be fine right now

2023-05-10 17:10 UTC, merged