Cu 862j4d59c walidacja klasy company
PRO-E-montazysta/PRO pull request #23
Opened 2023-01-24 20:52 UTC by s21670-Pyrzak-Tomasz-gr-18C

2023-01-24 20:52 UTC, s20146 commented
Task linked: [CU-862j4d59c walidacja klasy Company](https://app.clickup.com/t/862j4d59c)

2023-01-25 10:12 UTC, kurylek requested changes
We should remove `@NotNull` from `private Date createdAt;` Company.java:28 - value is generated

2023-01-25 10:12 UTC, kurylek commented on Java/E-montazysta/src/main/java/com/emontazysta/model/Company.java
> +    @NotNull
createdAt is generated on Company create- we don't pass it in body

2023-01-25 10:12 UTC, kurylek commented on Java/E-montazysta/src/main/java/com/emontazysta/model/Comment.java
>  }
Changes not related to Cu 862j4d59c

2023-01-25 10:57 UTC, kurylek approved these changes

2023-01-25 10:59 UTC, merged