Comment - utworzenie dto oraz mapera dla modelu. Dodanie adnotacji wa…
PRO-E-montazysta/PRO pull request #24
Opened 2023-01-24 21:24 UTC by s21670-Pyrzak-Tomasz-gr-18C

…lidacyjnych dla atrybutów klasy oraz kontrolera.

2023-01-24 21:24 UTC, s20146 commented
Task linked: [CU-862j4dk39 walidacja klasy comment](https://app.clickup.com/t/862j4dk39)

2023-01-25 10:23 UTC, kurylek requested changes
We should remove `@NotNull` from `private Date createdAt;` Comment.java:29 - value is generated

2023-01-25 10:23 UTC, kurylek commented on Java/E-montazysta/src/main/java/com/emontazysta/model/Comment.java
> +    @NotNull
Value is generated on Comment create- it's not passed in request body

2023-01-25 11:48 UTC, kurylek approved these changes

2023-01-25 11:51 UTC, merged