Asocjacje dla części klas dziedziczących po appUser. Utworzenie klasy…
PRO-E-montazysta/PRO pull request #33
Opened 2023-01-26 23:14 UTC by s21670-Pyrzak-Tomasz-gr-18C

… powiadomienia

2023-01-26 23:14 UTC, s20146 commented
Task linked: [CU-861m9q38d Asocjacje klas dziedziczących po AppUser](https://app.clickup.com/t/861m9q38d)

2023-01-27 08:19 UTC, kurylek requested changes
Some name changes required.

2023-01-27 08:19 UTC, kurylek commented on Java/E-montazysta/src/main/java/com/emontazysta/model/Comment.java
> +    private AppUser messageCreator;
messageCreator -> createdBy

2023-01-27 08:19 UTC, kurylek commented on Java/E-montazysta/src/main/java/com/emontazysta/model/Comment.java
> +    private List<AppUser> employees;
employees -> notify
But I would remove it, since there will be class Notification and we will use association with this class

2023-01-27 08:19 UTC, kurylek commented on Java/E-montazysta/src/main/java/com/emontazysta/model/DemandAdHoc.java
> +    private Foreman foreman;
foreman -> createdBy

2023-01-27 08:19 UTC, kurylek commented on Java/E-montazysta/src/main/java/com/emontazysta/model/DemandAdHoc.java
> +    private Manager manager;
manager -> notify
But I would remove it, since there will be class Notification and we will use association with this class

2023-01-27 08:19 UTC, kurylek commented on Java/E-montazysta/src/main/java/com/emontazysta/model/ElementReturnRelease.java
> +    private Foreman foreman;
foreman -> recivedBy
Missing association with Warehouseman- realeasedBy & receivedBy (in case that two different people did it?)

2023-01-27 08:19 UTC, kurylek commented on Java/E-montazysta/src/main/java/com/emontazysta/model/Fitter.java
> +    private List<OrderStage> orderStages;
orderStages -> workingOn

2023-01-27 08:19 UTC, kurylek commented on Java/E-montazysta/src/main/java/com/emontazysta/model/Notification.java
> +    private AppUser employee;
employee -> notify / notifiedEmployee ?

2023-01-27 08:19 UTC, kurylek commented on Java/E-montazysta/src/main/java/com/emontazysta/model/OrderStage.java
> +    private Foreman foreman;
foreman -> managedBy

2023-01-27 08:19 UTC, kurylek commented on Java/E-montazysta/src/main/java/com/emontazysta/model/OrderStage.java
> +    private List<Fitter> fitterList;
fitterList -> assignedTo

2023-01-27 08:19 UTC, kurylek commented on Java/E-montazysta/src/main/java/com/emontazysta/model/ToolEvent.java
> +    private AppUser employee;
employee -> createdBy

2023-01-27 08:19 UTC, kurylek commented on Java/E-montazysta/src/main/java/com/emontazysta/model/ToolEvent.java
> +    @ManyToOne Manager manager;
missing private
manager ->acceptedBy

2023-01-27 08:19 UTC, kurylek commented on Java/E-montazysta/src/main/java/com/emontazysta/model/ToolRelease.java
> +    private Foreman foreman;
foreman -> recivedBy
Missing associations with Warehouseman- realeasedBy & receivedBy (in case that two different people did it?)

2023-01-27 08:19 UTC, kurylek commented on Java/E-montazysta/src/main/java/com/emontazysta/model/Unavailability.java
> +    private AppUser manager;
manager -> createdBy/assignedBy

2023-01-27 08:19 UTC, kurylek commented on Java/E-montazysta/src/main/java/com/emontazysta/model/Unavailability.java
> +    private AppUser employee;
employee -> assignedTo

2023-01-27 08:19 UTC, kurylek commented on Java/E-montazysta/src/main/java/com/emontazysta/model/Orders.java
> +    private Manager manager;
manager -> managedBy

2023-01-27 08:19 UTC, kurylek commented on Java/E-montazysta/src/main/java/com/emontazysta/model/Orders.java
> +    private Foreman foreman;
foreman -> assignedTo

Missing association with Specialist(filledBy?) and SalesRepresentative (createdBy?)

2023-01-27 08:19 UTC, kurylek commented on Java/E-montazysta/src/main/java/com/emontazysta/model/Manager.java
> +    private List<Unavailability> unavailabilities;
unavailabilities -> createdUnavailabilities / assignedUnavailabilities

2023-01-27 08:19 UTC, kurylek commented on Java/E-montazysta/src/main/java/com/emontazysta/model/Manager.java
> +    private List<ToolEvent> events;
events -> acceptedEvents
Missing association with ElementEvents

2023-01-27 08:19 UTC, kurylek commented on Java/E-montazysta/src/main/java/com/emontazysta/model/Manager.java
> +    private List<Orders> orders;
orders -> managedOrders

2023-01-27 08:19 UTC, kurylek commented on Java/E-montazysta/src/main/java/com/emontazysta/model/Manager.java
> +    private List<DemandAdHoc> demandsAdHoc;
Might be replaced with List<Notification> receivedNotifications in AppUser?

2023-01-27 08:19 UTC, kurylek commented on Java/E-montazysta/src/main/java/com/emontazysta/model/ElementEvent.java
> +    private AppUser employee;
employee -> createdBy

Missing association with Manager acceptedBy

2023-01-27 08:19 UTC, kurylek commented on Java/E-montazysta/src/main/java/com/emontazysta/model/Foreman.java
> +    private List<DemandAdHoc> demandsAdHoc;
demandsAdHoc -> createdDemandsAdHoc

2023-01-27 08:19 UTC, kurylek commented on Java/E-montazysta/src/main/java/com/emontazysta/model/Foreman.java
> +    private List<Orders> orders;
orders -> assignedOrders

2023-01-27 08:19 UTC, kurylek commented on Java/E-montazysta/src/main/java/com/emontazysta/model/Foreman.java
> +    private List<OrderStage> ordersStagesList;
ordersStagesList -> managedOrdersStages

2023-01-27 08:19 UTC, kurylek commented on Java/E-montazysta/src/main/java/com/emontazysta/model/Foreman.java
> +    private List<ToolRelease> toolReleaseList;
toolReleaseList-> recivedTools

2023-01-27 08:19 UTC, kurylek commented on Java/E-montazysta/src/main/java/com/emontazysta/model/Foreman.java
> +    private List<ElementReturnRelease> elementsReturnsReleases;
elementsReturnsReleases -> recivedElements

2023-01-27 08:19 UTC, kurylek commented on Java/E-montazysta/src/main/java/com/emontazysta/model/Employee.java
>      private String pesel;
Missing unique validation

2023-01-27 08:19 UTC, kurylek commented on Java/E-montazysta/src/main/java/com/emontazysta/model/Employee.java
> +    private List<Employment> employments;
employments -> employmentHistory

2023-01-27 08:19 UTC, kurylek commented on Java/E-montazysta/src/main/java/com/emontazysta/model/Employee.java
> +    @OneToMany(mappedBy = "messageCreator")
messageCreator -> createdBy

2023-01-27 08:19 UTC, kurylek commented on Java/E-montazysta/src/main/java/com/emontazysta/model/Employee.java
> +    private List<Comment>  allComments;
Will be replaced with Notification?

2023-01-27 08:19 UTC, kurylek commented on Java/E-montazysta/src/main/java/com/emontazysta/model/Employee.java
> +    private List<ElementEvent> events;
events -> createdElementEvents

2023-01-27 08:19 UTC, kurylek commented on Java/E-montazysta/src/main/java/com/emontazysta/model/Employee.java
> +    private List<ToolEvent> toolEvents;
toolEvents-> createdToolEvents

2023-01-27 23:49 UTC, ksidor93 commented
![image](https://user-images.githubusercontent.com/21010951/215226684-a9a6cc91-c2de-47a1-a107-8ee28cc0e1e9.png)

2023-01-28 12:54 UTC, closed without merging