Cu 862j6m3h7 utworzenie szkieletu aplikacji i podpicie do routera s18288pejotedupl
PRO-E-montazysta/PRO pull request #64
Opened 2023-02-12 22:09 UTC by s18288

2023-02-12 22:09 UTC, s20146 commented
Task linked: [CU-862j6m3h7 Utworzenie szkieletu aplikacji i podpięcie do routera](https://app.clickup.com/t/862j6m3h7)

2023-02-13 11:33 UTC, kurylek requested changes
Need some changes in role names, fix in redirect after login (since we don't use /mock right now), and there is 'allowedRoles: [Role["*"]]' on every page, so eg. fitterr can see everything.

2023-02-13 11:33 UTC, kurylek commented on React/src/types/roleEnum.ts
> +    WAREHOUSEMAN = 'WAREHOUSEMAN',
Should be 'WAREHOUSE_MAN'

2023-02-13 11:33 UTC, kurylek commented on React/src/types/roleEnum.ts
> +    WAREHOUSE_MANAGER = 'WAREHOUSE MANAGER',
Should be 'WAREHOUSE_MANAGER'

2023-02-13 11:33 UTC, kurylek commented on React/src/types/roleEnum.ts
> +    EXPERT = 'EXPERT',
Should be 'SPECIALIST'

2023-02-13 11:33 UTC, kurylek commented on React/src/utils/pageList.tsx
> -                        path: '/mock',
Users were redirected to /mock after login, now they get 404 after login

2023-02-15 15:10 UTC, kurylek approved these changes
Would be nice if main page is first link in menu, but it works fine!

2023-02-16 20:45 UTC, merged