Cu 862j7nznx dto with associations for all class models piotr kryszkiewicz
PRO-E-montazysta/PRO pull request #72
Opened 2023-02-17 23:31 UTC by Kryhowsky

2023-02-17 23:31 UTC, s20146 commented
Task linked: [CU-862j7nznx DTO with associations for all class models](https://app.clickup.com/t/862j7nznx)

2023-02-20 21:17 UTC, kurylek requested changes
We have to map seeded data since we want to use DTO while adding

2023-02-23 13:37 UTC, kurylek requested changes

2023-02-23 13:37 UTC, kurylek commented on Java/E-montazysta/src/main/java/com/emontazysta/controller/AppUserController.java
>      @PostMapping("/create")
I think that we should use same mapping in every controller, so if we want to use POST at /create we should use it everywhere.

2023-02-23 13:37 UTC, kurylek commented on Java/E-montazysta/src/main/java/com/emontazysta/controller/ClientController.java
> +    @PostMapping("/create")
I think that we should use same mapping in every controller, so if we want to use POST at /create we should use it everywhere.

2023-02-23 13:37 UTC, kurylek commented on Java/E-montazysta/src/main/java/com/emontazysta/mapper/ClientMapper.java
> +//    private final CompanyService companyService;
YAGNI

2023-02-23 13:37 UTC, kurylek commented on Java/E-montazysta/src/main/java/com/emontazysta/model/Manager.java
> +    private List<ElementEvent> elementEvents; //TODO: duplicated from Employee?
In Employee it says who added ElementEvent, here it says which ElementEvents were accepted by this Manager

2023-02-23 13:37 UTC, kurylek commented on Java/E-montazysta/src/main/java/com/emontazysta/model/dto/NotificationDto.java
> +    private Long orderStageId;
It will change, but for now it's fine

2023-02-23 13:37 UTC, kurylek commented on Java/E-montazysta/src/main/java/com/emontazysta/mapper/NotificationMapper.java
> +public class NotificationMapper {
It will change soon, but for now it's fine

2023-02-23 13:37 UTC, kurylek commented on Java/E-montazysta/src/main/java/com/emontazysta/mapper/ElementInWarehouseMapper.java
> +                .warehouse(elementInWarehouseDto.getWarehouseId() == null ? null : warehouseRepository.getReferenceById(elementInWarehouseDto.getWarehouseId()))
Where is some problem with nulls

2023-02-23 13:39 UTC, kurylek commented on Java/E-montazysta/src/main/java/com/emontazysta/controller/AppUserController.java
>      @PostMapping("/create")
Same in ClientController and CommentController

2023-02-23 16:21 UTC, kurylek approved these changes

2023-02-23 16:48 UTC, merged