dodanie tabeli pracownikow, i okna szczegołów pracownika
PRO-E-montazysta/PRO pull request #98
Opened 2023-03-07 19:30 UTC by Marcin-H

2023-03-07 19:30 UTC, s20146 commented
Task linked: [CU-862j2kn1y EmployeeComponent](https://app.clickup.com/t/862j2kn1y)

2023-03-07 20:11 UTC, kurylek requested changes
Patryk is doing deatails page here-
https://github.com/s20146/PRO/tree/CU-862jbajnc_OrderDetailsPage_Patryk-Kpisty
I think we should use one way to display details

2023-03-07 20:11 UTC, kurylek commented on React/src/api/user.api.ts
> +export const getAllUsers2 = () => {
```suggestion
export const getAllUsers = () => {
```

2023-03-07 20:11 UTC, kurylek commented on React/src/api/user.api.ts
> +export const getAllUsers = (payload: PayloadProps) => {
```suggestion
export const getFilteredUsers = (payload: PayloadProps) => {
```

2023-03-07 20:11 UTC, kurylek commented on React/src/api/user.api.ts
> +export const getUser = (id:string) =>{
```suggestion
export const getUserById = (id:string) =>{
```

2023-03-07 20:11 UTC, kurylek commented on React/src/pages/employees/Employees.tsx
> +        console.log(row);
```suggestion
```

2023-03-07 20:11 UTC, kurylek commented on React/src/pages/employees/employeesDetails/EmpDetails.tsx
> +// import { styled } from '@mui/material/styles';
```suggestion
```

2023-03-07 20:11 UTC, kurylek commented on React/src/pages/employees/employeesDetails/EmpDetails.tsx
> +  console.log(queryData);
```suggestion
```

2023-03-07 20:11 UTC, kurylek commented on React/src/pages/employees/helper.ts
> +    },
It doesn't work, it should be added as multiselect with defined values

2023-03-07 20:11 UTC, kurylek commented on React/src/pages/employees/helper.ts
> +    },
We shouldn't display enum. 
Here you can se how Patryk translated enum https://github.com/s20146/PRO/blob/489e8837ec9476b211d004690ee1aefbe7d90ebc/React/src/pages/orders/helper.ts#L53

2023-03-07 20:11 UTC, kurylek commented on React/src/pages/orders/index.tsx
> +        console.log(row);
```suggestion
```

2023-03-07 20:11 UTC, kurylek commented on React/src/utils/pageList.tsx
> +                        allowedRoles: [Role.FITTER, Role.SPECIALIST, Role.MANAGER, Role.SALES_REPRESENTATIVE, Role.FOREMAN, Role['*']],
```suggestion
                        allowedRoles: [Role.FITTER, Role.SPECIALIST, Role.MANAGER, Role.SALES_REPRESENTATIVE, Role.FOREMAN, Role.WAREHOUSE_MAN, Role.WAREHOUSE_MANAGER, Role['*']],
```

2023-03-07 20:11 UTC, kurylek commented on React/src/pages/employees/employeesDetails/EmpDetails.tsx
> +              R
How about getting 1st letters of first and last name?

2023-03-07 21:10 UTC, s21461 reviewed
walimy na razie tylko na końcówkę /filter nie na końcówkę /all
wrzuć tego prittiera którego Ci podesłałem i zformatuj pliki,
sprawdź o co chodzi i ikonką WorkHistoryIcon - nie ma jej w spisie ikonek od mui
https://mui.com/material-ui/material-icons/?query=WorkHistoryIcon

2023-03-11 12:13 UTC, kurylek approved these changes

2023-03-11 12:13 UTC, merged